In [3]:
import numpy as np

In [10]:
# crete a  4 x 4 matrix
my_array = np.array([[2,3,5,7],[11,13,17,19],
                     [23,29,31,37,], [41,43,47,49]])
my_array

array([[ 2,  3,  5,  7],
       [11, 13, 17, 19],
       [23, 29, 31, 37],
       [41, 43, 47, 49]])

In [5]:
my_array[1,1]

13

In [9]:
# get row #2
my_array[1,:]

array([11, 13, 17, 19])

In [8]:
# get column #2
my_array[:,1]

array([ 3, 13, 29, 43])

In [12]:
# get #2,#3 rows
my_array[1:3,:]

array([[11, 13, 17, 19],
       [23, 29, 31, 37]])

In [13]:
# get rows #2,3 and columns #1,2
my_array[1:3,0:2]

array([[11, 13],
       [23, 29]])

In [15]:
# get rows #2,3 and columns #1,3
my_array[1:3,[0,2]]

array([[11, 17],
       [23, 31]])